[31mData point [2.98767818 3.80924975] is not unique. 1 duplicates registered. Continuing ...[39m
[31mData point [2.98767792 3.80923945] is not unique. 2 duplicates registered. Continuing ...[39m
{'target': 0.29412278785313906, 'params': {'sigma': 2.9876897327194065, 'vmin': 3.809249456220631}}
[31mData point [0. 1.] is not unique. 1 duplicates registered. Continuing ...[39m
[31mData point [0. 1.] is not unique. 2 duplicates registered. Continuing ...[39m
[31mData point [0. 1.] is not unique. 3 duplicates registered. Continuing ...[39m
[31mData point [0. 1.] is not unique. 4 duplicates registered. Continuing ...[39m
[31mData point [0. 1.] is not unique. 5 duplicates registered. Continuing ...[39m
[31mData point [0. 1.] is not unique. 6 duplicates registered. Continuing ...[39m
[31mData point [0. 1.] is not unique. 7 duplicates registered. Continuing ...[39m
[31mData point [0. 1.] is not unique. 8 duplicates registered. Continuing ...[39m
[31mData point [14.999  5.   ] is not unique. 1 duplicates registered. Continuing ...[39m
[31mData point [14.999  5.   ] is not unique. 2 duplicates registered. Continuing ...[39m
[31mData point [14.999  5.   ] is not unique. 3 duplicates registered. Continuing ...[39m
[31mData point [14.999  5.   ] is not unique. 4 duplicates registered. Continuing ...[39m
[31mData point [14.999  5.   ] is not unique. 5 duplicates registered. Continuing ...[39m
[31mData point [14.999  5.   ] is not unique. 6 duplicates registered. Continuing ...[39m
[31mData point [14.86225463  5.        ] is not unique. 7 duplicates registered. Continuing ...[39m
[31mData point [14.999  5.   ] is not unique. 8 duplicates registered. Continuing ...[39m
[31mData point [14.999  5.   ] is not unique. 9 duplicates registered. Continuing ...[39m
[31mData point [14.999  5.   ] is not unique. 10 duplicates registered. Continuing ...[39m
[31mData point [14.999  5.   ] is not unique. 11 duplicates registered. Continuing ...[39m
[31mData point [14.999  5.   ] is not unique. 12 duplicates registered. Continuing ...[39m
[31mData point [14.86225463  5.        ] is not unique. 13 duplicates registered. Continuing ...[39m
[31mData point [14.999  5.   ] is not unique. 14 duplicates registered. Continuing ...[39m
{'target': 0.3724279336191325, 'params': {'kernel': 14.86225462523524, 'vmin': 5.0}}
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
{'target': 0.2736430561712468, 'params': {'kernel': 14.22004143950987, 'vmin': 4.822070443174376}}
/home/work/.local/lib/python3.10/site-packages/nilearn/image/resampling.py:809: UserWarning: Casting data from int16 to float32
  return resample_img(
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
/home/work/.local/lib/python3.10/site-packages/nilearn/image/resampling.py:809: UserWarning: Casting data from int16 to float32
  return resample_img(
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
[31mData point [13.84080084  5.        ] is not unique. 1 duplicates registered. Continuing ...[39m
{'target': 0.4208027055238925, 'params': {'kernel': 13.613373882208002, 'vmin': 5.0}}
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
[31mData point [14.999  5.   ] is not unique. 1 duplicates registered. Continuing ...[39m
[31mData point [14.999  5.   ] is not unique. 2 duplicates registered. Continuing ...[39m
[31mData point [14.999  5.   ] is not unique. 3 duplicates registered. Continuing ...[39m
[31mData point [14.999  5.   ] is not unique. 4 duplicates registered. Continuing ...[39m
[31mData point [14.999  5.   ] is not unique. 5 duplicates registered. Continuing ...[39m
[31mData point [14.8311853  5.       ] is not unique. 6 duplicates registered. Continuing ...[39m
[31mData point [14.999  5.   ] is not unique. 7 duplicates registered. Continuing ...[39m
[31mData point [14.999  5.   ] is not unique. 8 duplicates registered. Continuing ...[39m
[31mData point [14.999  5.   ] is not unique. 9 duplicates registered. Continuing ...[39m
[31mData point [14.999  5.   ] is not unique. 10 duplicates registered. Continuing ...[39m
[31mData point [14.999  5.   ] is not unique. 11 duplicates registered. Continuing ...[39m
[31mData point [14.999  5.   ] is not unique. 12 duplicates registered. Continuing ...[39m
[31mData point [14.999  5.   ] is not unique. 13 duplicates registered. Continuing ...[39m
[31mData point [14.999  5.   ] is not unique. 14 duplicates registered. Continuing ...[39m
[31mData point [14.999  5.   ] is not unique. 15 duplicates registered. Continuing ...[39m
[31mData point [14.999  5.   ] is not unique. 16 duplicates registered. Continuing ...[39m
[31mData point [14.999  5.   ] is not unique. 17 duplicates registered. Continuing ...[39m
{'target': 0.383826555628496, 'params': {'kernel': 14.831185297516445, 'vmin': 5.0}}
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py:308: UserWarning: empty mask
  ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
[31mData point [9.999      4.17534043] is not unique. 1 duplicates registered. Continuing ...[39m
{'target': 0.31343622832903123, 'params': {'kernel': 9.999, 'vmin': 4.175325430898562}}
Exception ignored in: <function TransformNode.set_children.<locals>.<lambda> at 0x7f1dbb330ee0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/transforms.py", line 198, in <lambda>
    self, lambda _, pop=child._parents.pop, k=id_self: pop(k))
KeyboardInterrupt: 
Process ForkPoolWorker-6229:
Process ForkPoolWorker-6230:
Process ForkPoolWorker-6231:
Traceback (most recent call last):
Process ForkPoolWorker-6228:
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/usr/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/usr/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
Process ForkPoolWorker-6227:
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
Process ForkPoolWorker-6222:
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/usr/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/usr/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
KeyboardInterrupt
Process ForkPoolWorker-6226:
Process ForkPoolWorker-6224:
Process ForkPoolWorker-6225:
Traceback (most recent call last):
Traceback (most recent call last):
Process ForkPoolWorker-6223:
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
Traceback (most recent call last):
Process ForkPoolWorker-6220:
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/usr/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/usr/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
KeyboardInterrupt
Process ForkPoolWorker-6216:
Process ForkPoolWorker-6221:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
Traceback (most recent call last):
KeyboardInterrupt
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
Process ForkPoolWorker-6219:
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
KeyboardInterrupt
  File "/usr/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/usr/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/usr/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
KeyboardInterrupt
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
KeyboardInterrupt
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/usr/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
Process ForkPoolWorker-6213:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/usr/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
KeyboardInterrupt
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/usr/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
Process ForkPoolWorker-6217:
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
Process ForkPoolWorker-6206:
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
Process ForkPoolWorker-6202:
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
KeyboardInterrupt
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 365, in get
    res = self._reader.recv_bytes()
  File "/usr/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
KeyboardInterrupt
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/work/.BBB/main.py", line 43, in do
    percentage_vol, avg_z_score = quantify_vol(s, "poor", vmin, vmin + dv, kernel, plot)
  File "/home/work/.BBB/utils.py", line 77, in quantify_vol
    plot_wrapper(subject, prognosis, ne, e, z_map, mean_pv, avg_z, vmin)
  File "/home/work/.BBB/utils.py", line 30, in plot_wrapper
    plot_stat_map(
  File "/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/img_plotting.py", line 1323, in plot_stat_map
    display = _plot_img_with_bg(
  File "/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/img_plotting.py", line 274, in _plot_img_with_bg
    display.add_overlay(
  File "/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py", line 308, in add_overlay
    ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
  File "/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py", line 392, in _map_show
    img = reorder_img(img, resample=resampling_interpolation)
  File "/home/work/.local/lib/python3.10/site-packages/nilearn/image/resampling.py", line 809, in reorder_img
    return resample_img(
  File "/home/work/.local/lib/python3.10/site-packages/nilearn/image/resampling.py", line 664, in resample_img
    _resample_one_img(
  File "/home/work/.local/lib/python3.10/site-packages/nilearn/image/resampling.py", line 306, in _resample_one_img
    affine_transform(
  File "/usr/local/lib/python3.10/dist-packages/scipy/ndimage/_interpolation.py", line 585, in affine_transform
    filtered = spline_filter(padded, order, output=numpy.float64,
  File "/usr/local/lib/python3.10/dist-packages/scipy/ndimage/_interpolation.py", line 204, in spline_filter
    spline_filter1d(input, order, axis, output=output, mode=mode)
  File "/usr/local/lib/python3.10/dist-packages/scipy/ndimage/_interpolation.py", line 132, in spline_filter1d
    _nd_image.spline_filter1d(input, order, axis, output, mode)
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/work/.BBB/main.py", line 43, in do
    percentage_vol, avg_z_score = quantify_vol(s, "poor", vmin, vmin + dv, kernel, plot)
  File "/home/work/.BBB/utils.py", line 77, in quantify_vol
    plot_wrapper(subject, prognosis, ne, e, z_map, mean_pv, avg_z, vmin)
  File "/home/work/.BBB/utils.py", line 30, in plot_wrapper
    plot_stat_map(
  File "/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/img_plotting.py", line 1323, in plot_stat_map
    display = _plot_img_with_bg(
  File "/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/img_plotting.py", line 300, in _plot_img_with_bg
    display.savefig(output_file)
  File "/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py", line 813, in savefig
    self.frame_axes.figure.savefig(
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/backend_bases.py", line 2193, in print_figure
    result = print_method(
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/backend_bases.py", line 2043, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/backends/backend_agg.py", line 497, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/backends/backend_agg.py", line 445, in _print_pil
    FigureCanvasAgg.draw(self)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/backends/backend_agg.py", line 388, in draw
    self.figure.draw(self.renderer)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/figure.py", line 3154, in draw
    mimage._draw_list_compositing_images(
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/axes/_base.py", line 3070, in draw
    mimage._draw_list_compositing_images(
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/text.py", line 747, in draw
    with self._cm_set(text=self._get_wrapped_text()):
  File "/usr/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/artist.py", line 1239, in _cm_set
    self.set(**orig_vals)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/artist.py", line 147, in <lambda>
    cls.set = lambda self, **kwargs: Artist.set(self, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/artist.py", line 1227, in set
    return self._internal_update(cbook.normalize_kwargs(kwargs, self))
KeyboardInterrupt
Process ForkPoolWorker-6214:
Process ForkPoolWorker-6204:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/PIL/ImageFile.py", line 536, in _save
    fh = fp.fileno()
AttributeError: '_idat' object has no attribute 'fileno'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/work/.BBB/main.py", line 43, in do
    percentage_vol, avg_z_score = quantify_vol(s, "poor", vmin, vmin + dv, kernel, plot)
  File "/home/work/.BBB/utils.py", line 77, in quantify_vol
    plot_wrapper(subject, prognosis, ne, e, z_map, mean_pv, avg_z, vmin)
  File "/home/work/.BBB/utils.py", line 30, in plot_wrapper
    plot_stat_map(
  File "/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/img_plotting.py", line 1323, in plot_stat_map
    display = _plot_img_with_bg(
  File "/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/img_plotting.py", line 300, in _plot_img_with_bg
    display.savefig(output_file)
  File "/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py", line 813, in savefig
    self.frame_axes.figure.savefig(
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/backend_bases.py", line 2193, in print_figure
    result = print_method(
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/backend_bases.py", line 2043, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/backends/backend_agg.py", line 497, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/backends/backend_agg.py", line 446, in _print_pil
    mpl.image.imsave(
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/image.py", line 1656, in imsave
    image.save(fname, **pil_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/PIL/Image.py", line 2439, in save
    save_handler(self, fp, filename)
  File "/usr/local/lib/python3.10/dist-packages/PIL/PngImagePlugin.py", line 1402, in _save
    ImageFile._save(im, _idat(fp, chunk), [("zip", (0, 0) + im.size, 0, rawmode)])
  File "/usr/local/lib/python3.10/dist-packages/PIL/ImageFile.py", line 540, in _save
    _encode_tile(im, fp, tile, bufsize, None, exc)
  File "/usr/local/lib/python3.10/dist-packages/PIL/ImageFile.py", line 559, in _encode_tile
    errcode, data = encoder.encode(bufsize)[1:]
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/PIL/ImageFile.py", line 536, in _save
    fh = fp.fileno()
AttributeError: '_idat' object has no attribute 'fileno'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/work/.BBB/main.py", line 43, in do
    percentage_vol, avg_z_score = quantify_vol(s, "poor", vmin, vmin + dv, kernel, plot)
  File "/home/work/.BBB/utils.py", line 77, in quantify_vol
    plot_wrapper(subject, prognosis, ne, e, z_map, mean_pv, avg_z, vmin)
  File "/home/work/.BBB/utils.py", line 30, in plot_wrapper
    plot_stat_map(
  File "/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/img_plotting.py", line 1323, in plot_stat_map
    display = _plot_img_with_bg(
  File "/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/img_plotting.py", line 300, in _plot_img_with_bg
    display.savefig(output_file)
  File "/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py", line 813, in savefig
    self.frame_axes.figure.savefig(
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/backend_bases.py", line 2193, in print_figure
    result = print_method(
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/backend_bases.py", line 2043, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/backends/backend_agg.py", line 497, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/backends/backend_agg.py", line 446, in _print_pil
    mpl.image.imsave(
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/image.py", line 1656, in imsave
    image.save(fname, **pil_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/PIL/Image.py", line 2439, in save
    save_handler(self, fp, filename)
  File "/usr/local/lib/python3.10/dist-packages/PIL/PngImagePlugin.py", line 1402, in _save
    ImageFile._save(im, _idat(fp, chunk), [("zip", (0, 0) + im.size, 0, rawmode)])
  File "/usr/local/lib/python3.10/dist-packages/PIL/ImageFile.py", line 540, in _save
    _encode_tile(im, fp, tile, bufsize, None, exc)
  File "/usr/local/lib/python3.10/dist-packages/PIL/ImageFile.py", line 559, in _encode_tile
    errcode, data = encoder.encode(bufsize)[1:]
KeyboardInterrupt
Process ForkPoolWorker-6209:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/PIL/ImageFile.py", line 536, in _save
    fh = fp.fileno()
AttributeError: '_idat' object has no attribute 'fileno'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/work/.BBB/main.py", line 43, in do
    percentage_vol, avg_z_score = quantify_vol(s, "poor", vmin, vmin + dv, kernel, plot)
  File "/home/work/.BBB/utils.py", line 77, in quantify_vol
    plot_wrapper(subject, prognosis, ne, e, z_map, mean_pv, avg_z, vmin)
  File "/home/work/.BBB/utils.py", line 30, in plot_wrapper
    plot_stat_map(
  File "/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/img_plotting.py", line 1323, in plot_stat_map
    display = _plot_img_with_bg(
  File "/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/img_plotting.py", line 300, in _plot_img_with_bg
    display.savefig(output_file)
  File "/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py", line 813, in savefig
    self.frame_axes.figure.savefig(
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/backend_bases.py", line 2193, in print_figure
    result = print_method(
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/backend_bases.py", line 2043, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/backends/backend_agg.py", line 497, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/backends/backend_agg.py", line 446, in _print_pil
    mpl.image.imsave(
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/image.py", line 1656, in imsave
    image.save(fname, **pil_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/PIL/Image.py", line 2439, in save
    save_handler(self, fp, filename)
  File "/usr/local/lib/python3.10/dist-packages/PIL/PngImagePlugin.py", line 1402, in _save
    ImageFile._save(im, _idat(fp, chunk), [("zip", (0, 0) + im.size, 0, rawmode)])
  File "/usr/local/lib/python3.10/dist-packages/PIL/ImageFile.py", line 540, in _save
    _encode_tile(im, fp, tile, bufsize, None, exc)
  File "/usr/local/lib/python3.10/dist-packages/PIL/ImageFile.py", line 559, in _encode_tile
    errcode, data = encoder.encode(bufsize)[1:]
KeyboardInterrupt
Process ForkPoolWorker-6218:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/PIL/ImageFile.py", line 536, in _save
    fh = fp.fileno()
AttributeError: '_idat' object has no attribute 'fileno'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/work/.BBB/main.py", line 43, in do
    percentage_vol, avg_z_score = quantify_vol(s, "poor", vmin, vmin + dv, kernel, plot)
  File "/home/work/.BBB/utils.py", line 77, in quantify_vol
    plot_wrapper(subject, prognosis, ne, e, z_map, mean_pv, avg_z, vmin)
  File "/home/work/.BBB/utils.py", line 30, in plot_wrapper
    plot_stat_map(
  File "/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/img_plotting.py", line 1323, in plot_stat_map
    display = _plot_img_with_bg(
  File "/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/img_plotting.py", line 300, in _plot_img_with_bg
    display.savefig(output_file)
  File "/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py", line 813, in savefig
    self.frame_axes.figure.savefig(
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/backend_bases.py", line 2193, in print_figure
    result = print_method(
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/backend_bases.py", line 2043, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/backends/backend_agg.py", line 497, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/backends/backend_agg.py", line 446, in _print_pil
    mpl.image.imsave(
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/image.py", line 1656, in imsave
    image.save(fname, **pil_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/PIL/Image.py", line 2439, in save
    save_handler(self, fp, filename)
Process ForkPoolWorker-6212:
  File "/usr/local/lib/python3.10/dist-packages/PIL/PngImagePlugin.py", line 1402, in _save
    ImageFile._save(im, _idat(fp, chunk), [("zip", (0, 0) + im.size, 0, rawmode)])
  File "/usr/local/lib/python3.10/dist-packages/PIL/ImageFile.py", line 540, in _save
    _encode_tile(im, fp, tile, bufsize, None, exc)
  File "/usr/local/lib/python3.10/dist-packages/PIL/ImageFile.py", line 559, in _encode_tile
    errcode, data = encoder.encode(bufsize)[1:]
KeyboardInterrupt
Process ForkPoolWorker-6208:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/work/.BBB/main.py", line 43, in do
    percentage_vol, avg_z_score = quantify_vol(s, "poor", vmin, vmin + dv, kernel, plot)
  File "/home/work/.BBB/utils.py", line 77, in quantify_vol
    plot_wrapper(subject, prognosis, ne, e, z_map, mean_pv, avg_z, vmin)
  File "/home/work/.BBB/utils.py", line 30, in plot_wrapper
    plot_stat_map(
  File "/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/img_plotting.py", line 1323, in plot_stat_map
    display = _plot_img_with_bg(
  File "/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/img_plotting.py", line 300, in _plot_img_with_bg
    display.savefig(output_file)
  File "/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py", line 813, in savefig
    self.frame_axes.figure.savefig(
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/backend_bases.py", line 2193, in print_figure
    result = print_method(
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/backend_bases.py", line 2043, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/backends/backend_agg.py", line 497, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/backends/backend_agg.py", line 445, in _print_pil
    FigureCanvasAgg.draw(self)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/backends/backend_agg.py", line 388, in draw
    self.figure.draw(self.renderer)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/figure.py", line 3154, in draw
    mimage._draw_list_compositing_images(
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/axes/_base.py", line 3070, in draw
    mimage._draw_list_compositing_images(
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/image.py", line 649, in draw
    im, l, b, trans = self.make_image(
  File "/usr/local/lib/python3.10/dist-packages/PIL/ImageFile.py", line 536, in _save
    fh = fp.fileno()
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/image.py", line 939, in make_image
    return self._make_image(self._A, bbox, transformed_bbox, clip,
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/image.py", line 561, in _make_image
    output_alpha = _resample(  # resample alpha channel
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/image.py", line 208, in _resample
    _image.resample(data, out, transform,
AttributeError: '_idat' object has no attribute 'fileno'

During handling of the above exception, another exception occurred:

KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/work/.BBB/main.py", line 43, in do
    percentage_vol, avg_z_score = quantify_vol(s, "poor", vmin, vmin + dv, kernel, plot)
  File "/home/work/.BBB/utils.py", line 77, in quantify_vol
    plot_wrapper(subject, prognosis, ne, e, z_map, mean_pv, avg_z, vmin)
  File "/home/work/.BBB/utils.py", line 30, in plot_wrapper
    plot_stat_map(
  File "/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/img_plotting.py", line 1323, in plot_stat_map
    display = _plot_img_with_bg(
  File "/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/img_plotting.py", line 300, in _plot_img_with_bg
    display.savefig(output_file)
  File "/home/work/.local/lib/python3.10/site-packages/nilearn/plotting/displays/_slicers.py", line 813, in savefig
    self.frame_axes.figure.savefig(
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/backend_bases.py", line 2193, in print_figure
    result = print_method(
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/backend_bases.py", line 2043, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/backends/backend_agg.py", line 497, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/backends/backend_agg.py", line 446, in _print_pil
    mpl.image.imsave(
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/image.py", line 1656, in imsave
    image.save(fname, **pil_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/PIL/Image.py", line 2439, in save
    save_handler(self, fp, filename)
  File "/usr/local/lib/python3.10/dist-packages/PIL/PngImagePlugin.py", line 1402, in _save
    ImageFile._save(im, _idat(fp, chunk), [("zip", (0, 0) + im.size, 0, rawmode)])
  File "/usr/local/lib/python3.10/dist-packages/PIL/ImageFile.py", line 540, in _save
    _encode_tile(im, fp, tile, bufsize, None, exc)
  File "/usr/local/lib/python3.10/dist-packages/PIL/ImageFile.py", line 559, in _encode_tile
    errcode, data = encoder.encode(bufsize)[1:]
KeyboardInterrupt
Process ForkPoolWorker-6211:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/PIL/ImageFile.py", line 536, in _save
    fh = fp.fileno()
AttributeError: '_idat' object has no attribute 'fileno'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/home/work/.BBB/main.py", line 47, in obj_func
    pool.starmap(do, zip(subjects, prognosis, qa))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 768, in get
    self.wait(timeout)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 765, in wait
    self._event.wait(timeout)
  File "/usr/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.10/threading.py", line 320, in wait
    waiter.acquire()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/work/.BBB/main.py", line 101, in <module>
    outcome = np.array(obj_func(params['vmin'], params['kernel']))
  File "/home/work/.BBB/main.py", line 46, in obj_func
    with Pool(processes=processes) as pool:
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 739, in __exit__
    self.terminate()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 657, in terminate
    self._terminate()
  File "/usr/lib/python3.10/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 695, in _terminate_pool
    cls._help_stuff_finish(inqueue, task_handler, len(pool))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 675, in _help_stuff_finish
    inqueue._rlock.acquire()
KeyboardInterrupt
[31mData point [4.41193602 3.        ] is not unique. 1 duplicates registered. Continuing ...[39m
[31mData point [4.41193602 3.        ] is not unique. 2 duplicates registered. Continuing ...[39m
[31mData point [4.41193602 3.        ] is not unique. 3 duplicates registered. Continuing ...[39m
{'target': 0.2971031311562018, 'params': {'kernel': 4.4119360188752, 'vmin': 3.0}}
Traceback (most recent call last):
  File "/home/work/.BBB/main.py", line 95, in <module>
    optimizer.maximize(init_points=init_points, n_iter=n_iter)
  File "/home/work/.local/lib/python3.10/site-packages/bayes_opt/bayesian_optimization.py", line 374, in maximize
    self.probe(x_probe, lazy=False)
  File "/home/work/.local/lib/python3.10/site-packages/bayes_opt/bayesian_optimization.py", line 245, in probe
    self._space.probe(params)
  File "/home/work/.local/lib/python3.10/site-packages/bayes_opt/target_space.py", line 373, in probe
    target = self.target_func(**params)
  File "/home/work/.BBB/main.py", line 47, in obj_func
    pool.starmap(do, zip(subjects, prognosis, qa))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 768, in get
    self.wait(timeout)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 765, in wait
    self._event.wait(timeout)
  File "/usr/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.10/threading.py", line 320, in wait
    waiter.acquire()
KeyboardInterrupt
{'target': 0.31343623789736363, 'params': {'kernel': 9.951802993378278, 'vmin': 4.174704682291516}}
Traceback (most recent call last):
  File "/home/work/.BBB/main.py", line 95, in <module>
    optimizer.maximize(init_points=init_points, n_iter=n_iter)
  File "/home/work/.local/lib/python3.10/site-packages/bayes_opt/bayesian_optimization.py", line 374, in maximize
    self.probe(x_probe, lazy=False)
  File "/home/work/.local/lib/python3.10/site-packages/bayes_opt/bayesian_optimization.py", line 245, in probe
    self._space.probe(params)
  File "/home/work/.local/lib/python3.10/site-packages/bayes_opt/target_space.py", line 373, in probe
    target = self.target_func(**params)
  File "/home/work/.BBB/main.py", line 47, in obj_func
    pool.starmap(do, zip(subjects, prognosis, qa))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 768, in get
    self.wait(timeout)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 765, in wait
    self._event.wait(timeout)
  File "/usr/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.10/threading.py", line 320, in wait
    waiter.acquire()
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/work/.BBB/main.py", line 95, in <module>
    optimizer.maximize(init_points=init_points, n_iter=n_iter)
  File "/home/work/.local/lib/python3.10/site-packages/bayes_opt/bayesian_optimization.py", line 374, in maximize
    self.probe(x_probe, lazy=False)
  File "/home/work/.local/lib/python3.10/site-packages/bayes_opt/bayesian_optimization.py", line 245, in probe
    self._space.probe(params)
  File "/home/work/.local/lib/python3.10/site-packages/bayes_opt/target_space.py", line 373, in probe
    target = self.target_func(**params)
  File "/home/work/.BBB/main.py", line 47, in obj_func
    pool.starmap(do, zip(subjects, prognosis, qa))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 768, in get
    self.wait(timeout)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 765, in wait
    self._event.wait(timeout)
  File "/usr/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.10/threading.py", line 320, in wait
    waiter.acquire()
KeyboardInterrupt
{'target': 0.3128678533406269, 'params': {'kernel': 4.602432191449302, 'vmin': 3.852156479791386}}
{'target': 0.25341444942038205, 'params': {'kernel': 3.134264079799038, 'vmin': 2.058874341842697}}
/home/work/.local/lib/python3.10/site-packages/nilearn/image/resampling.py:809: UserWarning: Casting data from int16 to float32
  return resample_img(
/home/work/.local/lib/python3.10/site-packages/nilearn/image/resampling.py:809: UserWarning: Casting data from int16 to float32
  return resample_img(
{'target': 0.33414462318752125, 'params': {'kernel': 7.937412773532873, 'vmin': 3.8403954820743835}}
{'target': 0.28238733462659016, 'params': {'kernel': 7.58390671346948, 'vmin': 3.723953002888085}}
{'target': 0.29270797163519907, 'params': {'kernel': 7.268897186608343, 'vmin': 4.227588014612152}}
Traceback (most recent call last):
  File "/home/work/.BBB/main.py", line 98, in <module>
    optimizer.maximize(init_points=init_points, n_iter=n_iter)
  File "/home/work/.local/lib/python3.10/site-packages/bayes_opt/bayesian_optimization.py", line 374, in maximize
    self.probe(x_probe, lazy=False)
  File "/home/work/.local/lib/python3.10/site-packages/bayes_opt/bayesian_optimization.py", line 245, in probe
    self._space.probe(params)
  File "/home/work/.local/lib/python3.10/site-packages/bayes_opt/target_space.py", line 373, in probe
    target = self.target_func(**params)
  File "/home/work/.BBB/main.py", line 48, in obj_func
    pool.starmap(do, zip(subjects, prognosis, qa))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 768, in get
    self.wait(timeout)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 765, in wait
    self._event.wait(timeout)
  File "/usr/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.10/threading.py", line 320, in wait
    waiter.acquire()
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/work/.BBB/main.py", line 98, in <module>
    optimizer.maximize(init_points=init_points, n_iter=n_iter)
  File "/home/work/.local/lib/python3.10/site-packages/bayes_opt/bayesian_optimization.py", line 374, in maximize
    self.probe(x_probe, lazy=False)
  File "/home/work/.local/lib/python3.10/site-packages/bayes_opt/bayesian_optimization.py", line 245, in probe
    self._space.probe(params)
  File "/home/work/.local/lib/python3.10/site-packages/bayes_opt/target_space.py", line 373, in probe
    target = self.target_func(**params)
  File "/home/work/.BBB/main.py", line 48, in obj_func
    pool.starmap(do, zip(subjects, prognosis, qa))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 768, in get
    self.wait(timeout)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 765, in wait
    self._event.wait(timeout)
  File "/usr/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.10/threading.py", line 320, in wait
    waiter.acquire()
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/work/.BBB/main.py", line 98, in <module>
    optimizer.maximize(init_points=init_points, n_iter=n_iter)
  File "/home/work/.local/lib/python3.10/site-packages/bayes_opt/bayesian_optimization.py", line 374, in maximize
    self.probe(x_probe, lazy=False)
  File "/home/work/.local/lib/python3.10/site-packages/bayes_opt/bayesian_optimization.py", line 245, in probe
    self._space.probe(params)
  File "/home/work/.local/lib/python3.10/site-packages/bayes_opt/target_space.py", line 373, in probe
    target = self.target_func(**params)
  File "/home/work/.BBB/main.py", line 48, in obj_func
    pool.starmap(do, zip(subjects, prognosis, qa))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 768, in get
    self.wait(timeout)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 765, in wait
    self._event.wait(timeout)
  File "/usr/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.10/threading.py", line 320, in wait
    waiter.acquire()
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/work/.BBB/main.py", line 98, in <module>
    optimizer.maximize(init_points=init_points, n_iter=n_iter)
  File "/home/work/.local/lib/python3.10/site-packages/bayes_opt/bayesian_optimization.py", line 374, in maximize
    self.probe(x_probe, lazy=False)
  File "/home/work/.local/lib/python3.10/site-packages/bayes_opt/bayesian_optimization.py", line 245, in probe
    self._space.probe(params)
  File "/home/work/.local/lib/python3.10/site-packages/bayes_opt/target_space.py", line 373, in probe
    target = self.target_func(**params)
  File "/home/work/.BBB/main.py", line 48, in obj_func
    pool.starmap(do, zip(subjects, prognosis, qa))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 768, in get
    self.wait(timeout)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 765, in wait
    self._event.wait(timeout)
  File "/usr/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.10/threading.py", line 320, in wait
    waiter.acquire()
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/work/.BBB/main.py", line 83, in <module>
    df = pd.read_excel("data/outcome.xlsx", header=0, usecols="A,C,G,H,I").iloc[:75]
  File "/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/excel/_base.py", line 490, in read_excel
    data = io.parse(
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/excel/_base.py", line 1734, in parse
    return self._reader.parse(
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/excel/_base.py", line 765, in parse
    data = self.get_sheet_data(sheet, convert_float, file_rows_needed)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/excel/_openpyxl.py", line 616, in get_sheet_data
    converted_row = [self._convert_cell(cell, convert_float) for cell in row]
KeyboardInterrupt
{'target': 0.056073100616631295, 'params': {'kernel': 0.3194157374031123, 'vmin': 0.16191592026485582}}
{'target': 0.22583837269578547, 'params': {'kernel': 0.2753900106686687, 'vmin': 0.22911515710646768}}
/home/work/.local/lib/python3.10/site-packages/nilearn/image/resampling.py:809: UserWarning: Casting data from int16 to float32
  return resample_img(
/home/work/.local/lib/python3.10/site-packages/nilearn/image/resampling.py:809: UserWarning: Casting data from int16 to float32
  return resample_img(
{'target': 0.27927978628291444, 'params': {'kernel': 0.7951069149179172, 'vmin': 0.2291990321575305}}
